/* P&P Distribuidora — datos del catálogo.
   Expuesto en window.PYP_CATALOG. Precios de lista mayorista (ARS), se confirman por WhatsApp.
   Los productos con `variants` muestran un selector de sabor/variedad en la tarjeta.
   Una variante puede traer su propio `price` (ej: Arroyito, Miel) — si no, se usa el `price` del producto. */

/* Resolucion de imagenes: en la pagina publicada el bundler reemplaza estas rutas
   por blobs inline via window.__resources; en preview normal usa la ruta tal cual. */
const __RES_IDS = {
  "assets/catalog-pub/masamadre-integral.png": "r1",
  "assets/catalog-pub/masamadre-salvado.png": "r2",
  "assets/catalog-pub/masamadre-aleman.png": "r3",
  "assets/catalog-pub/masamadre-calabaza.png": "r4",
  "assets/catalog-pub/masamadre-semillas-andinas.png": "r5",
  "assets/catalog-pub/masamadre-centeno.png": "r6",
  "assets/catalog-pub/masamadre-multicereal.png": "r7",
  "assets/catalog-pub/masamadre-parmesanitas.png": "r8",
  "assets/catalog-pub/panez-arabe.png": "r9",
  "assets/catalog-pub/panez-arabe-integral.png": "r10",
  "assets/catalog-pub/panez-molde.png": "r11",
  "assets/catalog-pub/panez-sandwichero.png": "r12",
  "assets/catalog-pub/panez-centeno.png": "r13",
  "assets/catalog-pub/pazzi-chips.png": "r14",
  "assets/catalog-pub/pazzi-chips-tradicional.png": "r15",
  "assets/catalog-pub/pazzi-burger.png": "r16",
  "assets/catalog-pub/pazzi-burger-queso.png": "r17",
  "assets/catalog-pub/pazzi-burger-semillas.png": "r18",
  "assets/catalog-pub/pazzi-pebete.png": "r19",
  "assets/catalog-pub/moms-variedades.png": "r24",
  "assets/catalog-pub/moms-proteicas.png": "r25",
  "assets/catalog-pub/nutricrack.png": "r26",
  "assets/catalog-pub/notter-mani.png": "r27",
  "assets/catalog-pub/rakan-pochoclo.jpeg": "r28",
  "assets/catalog-pub/ac-frola-brownie.png": "r29",
  "assets/catalog-pub/ac-frola-coco.png": "r30",
  "assets/catalog-pub/ac-frola-mixta.png": "r31",
  "assets/catalog-pub/ac-frola-membrillo.png": "r32",
  "assets/catalog-pub/ac-frola-ddl.png": "r33",
  "assets/catalog-pub/ac-frola-ddl-choco.png": "r34",
  "assets/catalog-pub/yaiza-pepas-membrillo.png": "r35",
  "assets/catalog-pub/ilcuoco-pepas.png": "r36",
  "assets/catalog-pub/ontrack-cuadrados.png": "r37",
  "assets/catalog-pub/jhosber-frutilla.png": "r38",
  "assets/catalog-pub/arroyito-alfajores.png": "r39",
  "assets/catalog-pub/chok-chocolate.png": "r40",
  "assets/catalog-pub/chok-chispas.png": "r41",
  "assets/catalog-pub/chok-praline.png": "r42",
  "assets/catalog-pub/chok-praline-blanco.png": "r43",
  "assets/catalog-pub/chok-glaseados.png": "r44",
  "assets/catalog-pub/chok-impalpables.png": "r45",
  "assets/catalog-pub/chok-maicena.png": "r46",
  "assets/catalog-pub/chok-mixtos.png": "r47",
  "assets/catalog-pub/chok-conitos.png": "r48",
  "assets/catalog-pub/altascumbres-variedades.png": "r49",
  "assets/catalog-pub/tomatto-pizzetas.png": "r50",
  "assets/catalog-pub/pampa-miel-solida.png": "r51",
  "assets/catalog-pub/pampa-miel-liquida.png": "r52",
  "assets/catalog-pub/pampa-miel-panal.png": "r53",
  "assets/logo-truck-full-pub.png": "r54"
};
function R(path) { return (window.__resources && window.__resources[__RES_IDS[path]]) || path; }
window.PYP_RES = R;

window.PYP_CATALOG = {
  whatsapp: "5491122924625",
  categories: [
    { id: "panificados", name: "Panificados", icon: "wheat", blurb: "Masa madre, panes, buns Pazzi y pizzetas artesanales de alta rotación." },
    { id: "galletas", name: "Galletas de Avena", icon: "cookie", blurb: "Mom's: plant based, sin conservantes. Caja surtida y línea proteica." },
    { id: "snacks", name: "Snacks & Crackers", icon: "popcorn", blurb: "Para picar y para el mostrador. 100% artesanal." },
    { id: "dulces", name: "Pastafrolas & Dulces", icon: "cake", blurb: "Pastafrolas, pepas y galletitas artesanales." },
    { id: "alfajores", name: "Alfajores", icon: "candy", blurb: "Alfajores y cuadrados, varios con línea sin TACC." },
    { id: "miel", name: "Miel Pampa", icon: "hexagon", blurb: "Miel pura de pradera: sólida, líquida y en panal." },
  ],
  products: [
    // ---- Panificados ----
    { id: "mm-integral", cat: "panificados", brand: "Masa Madre", name: "Pan de Masa Madre Integral", img: R("assets/catalog-pub/masamadre-integral.png"), desc: "Fermentación natural, miga húmeda y corteza rústica.", tags: ["Artesanal", "Integral"], price: 4200 },
    { id: "mm-salvado", cat: "panificados", brand: "Masa Madre", name: "Pan de Masa Madre con Salvado", img: R("assets/catalog-pub/masamadre-salvado.png"), desc: "Salvado de trigo, más fibra y sabor.", tags: ["Artesanal", "Con fibra"], price: 4200 },
    { id: "mm-aleman", cat: "panificados", brand: "Masa Madre", name: "Pan Tipo Alemán", img: R("assets/catalog-pub/masamadre-aleman.png"), desc: "Denso y nutritivo, ideal para fiambres.", tags: ["Artesanal"], price: 4200 },
    { id: "mm-calabaza", cat: "panificados", brand: "Masa Madre", name: "Pan de Molde Calabaza", img: R("assets/catalog-pub/masamadre-calabaza.png"), desc: "Pan de molde de masa madre con calabaza y avena.", tags: ["Artesanal"], price: 4200 },
    { id: "mm-semillas", cat: "panificados", brand: "Masa Madre", name: "Pan de Molde Semillas Andinas", img: R("assets/catalog-pub/masamadre-semillas-andinas.png"), desc: "Pan de molde de masa madre con semillas andinas.", tags: ["Artesanal"], price: 4200 },
    { id: "mm-centeno", cat: "panificados", brand: "Masa Madre", name: "Pan de Molde Centeno", img: R("assets/catalog-pub/masamadre-centeno.png"), desc: "Pan de molde de masa madre de centeno.", tags: ["Artesanal"], price: 4200 },
    { id: "mm-multicereal", cat: "panificados", brand: "Masa Madre", name: "Pan de Molde Multicereal", img: R("assets/catalog-pub/masamadre-multicereal.png"), desc: "Pan de molde de masa madre con mix de cereales y semillas.", tags: ["Artesanal"], price: 4200 },
    { id: "mm-parmesanitas", cat: "panificados", brand: "Masa Madre", name: "Parmesanitas", img: R("assets/catalog-pub/masamadre-parmesanitas.png"), desc: "Crackers de masa madre con queso, para picar.", tags: ["Artesanal", "Para picar"], price: 3200 },
    { id: "pz-arabe", cat: "panificados", brand: "Panez", name: "Pan Árabe", img: R("assets/catalog-pub/panez-arabe.png"), desc: "Clásico pan pita para rellenar.", tags: ["Práctico"], price: 2400 },
    { id: "pz-arabe-int", cat: "panificados", brand: "Panez", name: "Pan Árabe Integral", img: R("assets/catalog-pub/panez-arabe-integral.png"), desc: "Versión integral, fuente de fibra.", tags: ["Integral", "Con fibra"], price: 2400 },
    { id: "pz-sand-semillas", cat: "panificados", brand: "Panez", name: "Pan Sandwichero con Semillas", img: R("assets/catalog-pub/panez-sandwichero-semillas.webp"), desc: "Tierno y parejo, sin orillas duras, con semillas. Paquete x3 unidades.", tags: ["Práctico", "x3"], price: 2500 },
    { id: "pz-sand-queso", cat: "panificados", brand: "Panez", name: "Pan Sandwichero con Queso", img: R("assets/catalog-pub/panez-sandwichero-queso.webp"), desc: "Tierno y parejo, sin orillas duras, con queso gratinado. Paquete x3 unidades.", tags: ["Práctico", "x3"], price: 2500 },
    { id: "pz-sand-especias", cat: "panificados", brand: "Panez", name: "Pan Sandwichero con Especias", img: R("assets/catalog-pub/panez-sandwichero-especias.webp"), desc: "Tierno y parejo, sin orillas duras, con especias. Paquete x3 unidades.", tags: ["Práctico", "x3"], price: 2500 },
    { id: "pz-molde-centeno", cat: "panificados", brand: "Panez", name: "Pan de Molde Centeno", img: R("assets/catalog-pub/panez-molde-centeno.webp"), desc: "Pan de molde en fetas, sabor centeno. Rinde más por unidad, para sándwiches.", tags: ["Rinde más", "Integral"], price: 3000 },
    { id: "pz-molde-salvado", cat: "panificados", brand: "Panez", name: "Pan de Molde con Salvado", img: R("assets/catalog-pub/panez-molde-salvado.webp"), desc: "Pan de molde en fetas con salvado. Rinde más por unidad, para sándwiches.", tags: ["Rinde más", "Con fibra"], price: 3000 },
    { id: "pz-molde-integral", cat: "panificados", brand: "Panez", name: "Pan de Molde Integral", img: R("assets/catalog-pub/panez-molde-integral.webp"), desc: "Pan de molde en fetas integral. Rinde más por unidad, para sándwiches.", tags: ["Rinde más", "Integral"], price: 3000 },
    { id: "pa-chips-tradicional", cat: "panificados", brand: "Pazzi", name: "Chips Pazzi Tradicional", img: R("assets/catalog-pub/pazzi-chips-tradicional.png"), desc: "Chips de pan de papa, para picar, sabor tradicional.", tags: ["Pan de papa", "Para picar"], price: 1700 },
    { id: "pa-chips-queso", cat: "panificados", brand: "Pazzi", name: "Chips Pazzi con Queso", img: R("assets/catalog-pub/pazzi-chips.png"), desc: "Chips de pan de papa, para picar, con queso.", tags: ["Pan de papa", "Para picar"], price: 1700 },
    { id: "pa-burger", cat: "panificados", brand: "Pazzi", name: "Pan de Hamburguesa Clásico", img: R("assets/catalog-pub/pazzi-burger.png"), desc: "Pan de papa, esponjoso. Contiene 4 unidades.", tags: ["Pan de papa", "x4"], price: 2900 },
    { id: "pa-queso", cat: "panificados", brand: "Pazzi", name: "Pan de Hamburguesa con Queso", img: R("assets/catalog-pub/pazzi-burger-queso.png"), desc: "Con queso en la superficie, dorado al horno.", tags: ["Pan de papa", "x4"], price: 3600 },
    { id: "pa-semillas", cat: "panificados", brand: "Pazzi", name: "Pan de Hamburguesa con Semillas", img: R("assets/catalog-pub/pazzi-burger-semillas.png"), desc: "Topping de semillas, más textura.", tags: ["Pan de papa", "x4"], price: 3000 },
    { id: "pa-pebete", cat: "panificados", brand: "Pazzi", name: "Pebetes", img: R("assets/catalog-pub/pazzi-pebete.png"), desc: "Pebetes de pan de papa, listos para rellenar.", tags: ["Pan de papa"], price: 1700 },
    { id: "pa-pancho-xl-tradicional", cat: "panificados", brand: "Pazzi", name: "Pan de Pancho XL Tradicional", img: R("assets/catalog-pub/pazzi-pancho-xl.webp"), desc: "Panchos packs x 6 u. 85 gr · 5 cm de ancho x 22 cm de largo.", tags: ["Pan de papa", "x6"], price: 4000 },
    { id: "pa-pancho-xl-semillas", cat: "panificados", brand: "Pazzi", name: "Pan de Pancho XL con Semillas", img: R("assets/catalog-pub/pazzi-pancho-xl-semillas.webp"), desc: "Panchos packs x 6 u. 85 gr · 5 cm de ancho x 22 cm de largo.", tags: ["Pan de papa", "x6"], price: 4100 },
    { id: "pa-pancho-xl-queso", cat: "panificados", brand: "Pazzi", name: "Pan de Pancho XL con Queso", img: R("assets/catalog-pub/pazzi-pancho-xl-queso.webp"), desc: "Panchos packs x 6 u. 85 gr · 5 cm de ancho x 22 cm de largo.", tags: ["Pan de papa", "x6"], price: 5500 },
    { id: "to-pizzetas", cat: "panificados", brand: "Tomatito", name: "Pizzetas de Tomate", img: R("assets/catalog-pub/tomatto-pizzetas.png"), desc: "Pizzetas de tomate listas para hornear. Vienen en paquete de 12 unidades.", tags: ["x12"], price: 1650 },

    // ---- Galletas Mom's ----
    { id: "mo-surtidas", cat: "galletas", brand: "Mom's", name: "Galletas de Avena Surtidas", img: R("assets/catalog-pub/moms-variedades-hq.webp"), desc: "Caja de 10 unidades surtidas: chocolate, coco, granola, arándanos, mix de frutos secos, pasas de uva, maní con chocolate, cacao y naranja, limón y chocolate blanco.", tags: ["Plant based", "Caja x10 surtida"], price: 12750 },
    { id: "mo-avena", cat: "galletas", brand: "Mom's", name: "Galletas de Avena", img: R("assets/catalog-pub/moms-variedades-hq.webp"), desc: "Caja de 10 unidades del mismo sabor. Elegí el sabor.", tags: ["Plant based", "Caja x10"], price: 12750, variants: ["Chocolate", "Coco", "Granola", "Arándanos", "Mix de frutos secos", "Pasas de uva", "Maní con chocolate", "Cacao y naranja", "Limón", "Chocolate blanco"] },
    { id: "mo-proteicas", cat: "galletas", brand: "Mom's", name: "Galletas Proteicas", img: R("assets/catalog-pub/moms-proteicas-hq.webp"), desc: "Caja de 10 unidades del mismo sabor. 12 g de proteína por galleta, 100% vegano. Elegí el sabor.", tags: ["Proteica", "12g proteína", "Vegano", "Caja x10"], price: 12750, variants: ["Black", "Dubai", "Lemon Pie", "Choco blanco y arándanos", "Chocolate y nuez"] },
    { id: "mo-proteicas-surtidas", cat: "galletas", brand: "Mom's", name: "Galletas Proteicas Surtidas", img: R("assets/catalog-pub/moms-proteicas-hq.webp"), desc: "Caja de 10 unidades surtidas: Black, Dubai, Lemon Pie, Choco blanco y arándanos, Chocolate y nuez.", tags: ["Proteica", "12g proteína", "Vegano", "Caja x10 surtida"], price: 12750 },

    // ---- Snacks & Crackers ----
    { id: "nc-queso", cat: "snacks", brand: "Nutri Crack", name: "Crackers Integrales Queso", img: R("assets/catalog-pub/nutricrack-queso.webp"), desc: "Crackers integrales 100% artesanales, sabor queso.", tags: ["Integral", "Artesanal"], price: 2250 },
    { id: "nc-capresse", cat: "snacks", brand: "Nutri Crack", name: "Crackers Integrales Capresse", img: R("assets/catalog-pub/nutricrack-capresse.webp"), desc: "Crackers integrales 100% artesanales, sabor capresse.", tags: ["Integral", "Artesanal"], price: 2250 },
    { id: "nc-semillas", cat: "snacks", brand: "Nutri Crack", name: "Crackers Integrales Semillas", img: R("assets/catalog-pub/nutricrack-semillas.webp"), desc: "Crackers integrales 100% artesanales, con semillas.", tags: ["Integral", "Artesanal"], price: 2250 },
    { id: "nc-semillas-agridulces", cat: "snacks", brand: "Nutri Crack", name: "Cookies Integrales Semillas Agridulces", img: R("assets/catalog-pub/nutricrack-semillas-agridulces.webp"), desc: "Cookies integrales 100% artesanales, semillas agridulces.", tags: ["Integral", "Artesanal"], price: 2250 },
    { id: "no-mani", cat: "snacks", brand: "Nötter", name: "Maní con Cobertura", img: R("assets/catalog-pub/notter-mani-surtido.webp"), desc: "Bolsas de 200 g. Se vende por caja de 10 unidades (2 kg en total). Sabores surtidos: salame, pizza, jamón y queso.", tags: ["Para picar", "200 g c/u", "Caja x10 (2 kg)"], price: 29850 },
    { id: "rk-pochoclo", cat: "snacks", brand: "Rakan", name: "Pochoclo", img: R("assets/catalog-pub/rakan-pochoclo.jpeg"), desc: "Pochoclo liviano, 150 g. Ideal para el mostrador.", tags: ["Para picar", "150 g"], price: 2600 },
    { id: "ch-mani-chocolate", cat: "snacks", brand: "Chok", name: "Maní con Chocolate Chok", img: R("assets/catalog-pub/chok-mani-chocolate.webp"), desc: "Maní bañado en chocolate, aprox. 120 g.", tags: ["Para picar", "120 g"], price: 2300 },
    { id: "ch-bocaditos", cat: "snacks", brand: "Chok", name: "Bocaditos Chok", img: R("assets/catalog-pub/chok-bocaditos.webp"), desc: "Bocaditos bañados en chocolate, bolsa x12.", tags: ["Para picar", "Bolsa x12"], price: 4200 },
    { id: "mm-talitas", cat: "snacks", brand: "Masa Madre", name: "Talitas Masa Madre", img: R("assets/catalog-pub/masamadre-talitas.webp"), desc: "Crackers artesanales de masa madre, 150 g. Elegí el sabor.", tags: ["Artesanal", "150 g"], price: 2700, variants: ["Clásica", "Rúcula-Parmesano", "Tomate-Albahaca", "Multicereal", "Pizza", "Cúrcuma-Pimienta", "Orégano", "Queso-Cebolla", "Calabaza-Curry", "Pimentón", "Queso", "Integral", "Romero-Aceituna"] },

    // ---- Pastafrolas & Dulces ----
    { id: "ac-brownie", cat: "dulces", brand: "AC Artesanal", name: "Pastafrola Sabor Brownie", img: R("assets/catalog-pub/ac-frola-brownie.png"), desc: "Masa de cacao, intensa. Sin conservantes.", tags: ["Artesanal", "Sin conservantes"], price: 5100 },
    { id: "ac-coco", cat: "dulces", brand: "AC Artesanal", name: "Pastafrola Sabor Coco", img: R("assets/catalog-pub/ac-frola-coco.png"), desc: "Con coco rallado, dulzor justo.", tags: ["Artesanal"], price: 5100 },
    { id: "ac-mixta", cat: "dulces", brand: "AC Artesanal", name: "Pastafrola Mixta", img: R("assets/catalog-pub/ac-frola-mixta.png"), desc: "Membrillo y batata, la combinación clásica.", tags: ["Artesanal"], price: 5100 },
    { id: "ac-membrillo", cat: "dulces", brand: "AC Artesanal", name: "Pastafrola Sabor Membrillo", img: R("assets/catalog-pub/ac-frola-membrillo.png"), desc: "El clásico de membrillo, enrejado a mano. Sin conservantes.", tags: ["Artesanal", "Sin conservantes"], price: 5100 },
    { id: "ac-ddl", cat: "dulces", brand: "AC Artesanal", name: "Pastafrola Sabor Dulce de Leche", img: R("assets/catalog-pub/ac-frola-ddl-new.webp"), desc: "Relleno de dulce de leche, 100% calidad artesanal.", tags: ["Artesanal"], price: 5100 },
    { id: "ac-ddl-choco", cat: "dulces", brand: "AC Artesanal", name: "Pastafrola Dulce de Leche y Chocolate", img: R("assets/catalog-pub/ac-frola-ddl-choco.png"), desc: "Dulce de leche con hilos de chocolate. Una tradición familiar.", tags: ["Artesanal"], price: 5100 },
    { id: "ac-batata", cat: "dulces", brand: "AC Artesanal", name: "Pastafrola Sabor Batata", img: R("assets/catalog-pub/ac-frola-batata.webp"), desc: "Masa artesanal rellena con dulce de batata. Sin conservantes.", tags: ["Artesanal", "Sin conservantes"], price: 5100 },
    { id: "ac-membrillo-choco", cat: "dulces", brand: "AC Artesanal", name: "Pastafrola Membrillo y Chocolate", img: R("assets/catalog-pub/ac-frola-membrillo-chocolate.webp"), desc: "Relleno de membrillo con hilos de chocolate. Sin conservantes.", tags: ["Artesanal", "Sin conservantes"], price: 5100 },
    { id: "ya-pepas-arandanos", cat: "dulces", brand: "Yaiza", name: "Pepas Yaiza Dulce de Arándanos", img: R("assets/catalog-pub/yaiza-pepas-arandanos.webp"), desc: "Galletitas integrales con semillas de chía, rellenas con dulce de arándanos.", tags: ["Integral"], price: 2900 },
    { id: "ya-pepas-frutilla", cat: "dulces", brand: "Yaiza", name: "Pepas Yaiza Dulce de Frutilla", img: R("assets/catalog-pub/yaiza-pepas-frutilla.webp"), desc: "Galletitas sabor vainilla, rellenas con dulce de frutilla.", tags: ["Artesanal"], price: 2900 },
    { id: "ya-pepas-batata", cat: "dulces", brand: "Yaiza", name: "Pepas Yaiza Dulce de Batata", img: R("assets/catalog-pub/yaiza-pepas-batata.webp"), desc: "Galletitas sabor vainilla, rellenas con dulce de batata.", tags: ["Artesanal"], price: 2900 },
    { id: "ya-pepas-frutos-bosque", cat: "dulces", brand: "Yaiza", name: "Pepas Yaiza Frutos del Bosque", img: R("assets/catalog-pub/yaiza-pepas-frutos-del-bosque.webp"), desc: "Galletitas de algarroba y avena, rellenas con dulce de frutos del bosque.", tags: ["Algarroba"], price: 2900 },
    { id: "ya-pepas-membrillo", cat: "dulces", brand: "Yaiza", name: "Pepas Yaiza Dulce de Membrillo", img: R("assets/catalog-pub/yaiza-pepas-membrillo-new.webp"), desc: "Galletitas sabor vainilla, rellenas con dulce de membrillo.", tags: ["Artesanal"], price: 2900 },
    { id: "il-pepas-durazno", cat: "dulces", brand: "Il Cuoco", name: "Pepas Il Cuoco Avena y Algarroba con Duraznos", img: R("assets/catalog-pub/ilcuoco-pepas-durazno-algarroba.webp"), desc: "Pepas de avena y algarroba rellenas con mermelada de duraznos, 250 g.", tags: ["Artesanal", "250 g"], price: 2900 },
    { id: "il-pepas-membrillo", cat: "dulces", brand: "Il Cuoco", name: "Pepas Artesanales Il Cuoco Membrillo, Sésamo y Lino", img: R("assets/catalog-pub/ilcuoco-pepas-membrillo.webp"), desc: "Pepas de harina integral y avena con mermelada de membrillos y semillas de sésamo y lino, 250 g.", tags: ["Artesanal", "250 g"], price: 2900 },
    { id: "il-pepas-membrillo-algarroba", cat: "dulces", brand: "Il Cuoco", name: "Pepas Il Cuoco Integral y Algarroba con Membrillo", img: R("assets/catalog-pub/ilcuoco-pepas-membrillo-algarroba.webp"), desc: "Pepas de harina integral y algarroba rellenas con mermelada de membrillos, 250 g.", tags: ["Artesanal", "250 g"], price: 2900 },
    { id: "ot-cuadrados", cat: "dulces", brand: "On Track", name: "Cuadrados sin TACC", img: R("assets/catalog-pub/ontrack-cuadrados-hq.webp"), desc: "Caja surtida de 12 unidades libres de gluten, 80 g c/u: tarta con mermelada de membrillo, tarta con coco rellena con dulce de leche, brownie con nuez.", tags: ["Sin TACC", "Caja x12 surtida"], price: 20900 },
    { id: "jh-merengadas", cat: "dulces", brand: "J. Hosber", name: "Galletitas Merengadas · Frutilla", img: R("assets/catalog-pub/jhosber-frutilla.png"), desc: "Galletitas rellenas sabor frutilla, 195 g.", tags: ["Dulce"], price: 2700 },

    // ---- Alfajores ----
    { id: "ar-alfajor-caja12", cat: "alfajores", brand: "Arroyito", name: "Alfajores Arroyito Caja x12", img: R("assets/catalog-pub/arroyito-alfajores-variedades.webp"), desc: "Caja de 12 unidades del mismo sabor. Elegí la variedad.", tags: ["Artesanal", "Caja x12"], variants: [{ name: "Bomba", price: 51000 }, { name: "Dinamita", price: 42000 }, { name: "Molotov", price: 36000 }] },
    { id: "ar-alfajor-surtidos", cat: "alfajores", brand: "Arroyito", name: "Alfajores Arroyito Caja x12 Surtidos", img: R("assets/catalog-pub/arroyito-alfajores-variedades.webp"), desc: "Caja de 12 unidades surtidas: Bomba, Dinamita y Molotov.", tags: ["Artesanal", "Caja x12 surtida"], price: 44400 },
    { id: "ch-chocolate", cat: "alfajores", brand: "Chok", name: "Alfajor Chok Chocolate", img: R("assets/catalog-pub/chok-chocolate.png"), desc: "Alfajor artesanal sabor chocolate, pote de ~200 g.", tags: ["Artesanal", "~200 g"], price: 3800 },
    { id: "ch-chispas", cat: "alfajores", brand: "Chok", name: "Alfajor Chok Chocolate con Chispas", img: R("assets/catalog-pub/chok-chispas.png"), desc: "Alfajor artesanal con chispas de chocolate, pote de ~200 g.", tags: ["Artesanal", "~200 g"], price: 3800 },
    { id: "ch-praline", cat: "alfajores", brand: "Chok", name: "Alfajor Chok Chocolate con Praliné", img: R("assets/catalog-pub/chok-praline.png"), desc: "Alfajor artesanal con praliné, pote de ~200 g.", tags: ["Artesanal", "~200 g"], price: 3800 },
    { id: "ch-praline-blanco", cat: "alfajores", brand: "Chok", name: "Alfajor Chok Praliné Blanco", img: R("assets/catalog-pub/chok-praline-blanco.png"), desc: "Alfajor artesanal con praliné blanco, pote de ~200 g.", tags: ["Artesanal", "~200 g"], price: 3800 },
    { id: "ch-glaseados", cat: "alfajores", brand: "Chok", name: "Alfajor Chok Glaseado", img: R("assets/catalog-pub/chok-glaseados.png"), desc: "Alfajor artesanal glaseado, pote de ~200 g.", tags: ["Artesanal", "~200 g"], price: 3800 },
    { id: "ch-impalpables", cat: "alfajores", brand: "Chok", name: "Alfajor Chok Azúcar Impalpable", img: R("assets/catalog-pub/chok-impalpables.png"), desc: "Alfajor artesanal con azúcar impalpable, pote de ~200 g.", tags: ["Artesanal", "~200 g"], price: 3800 },
    { id: "ch-maicena", cat: "alfajores", brand: "Chok", name: "Alfajor Chok Maicena", img: R("assets/catalog-pub/chok-maicena.png"), desc: "Alfajor artesanal de maicena, pote de ~200 g.", tags: ["Artesanal", "~200 g"], price: 3800 },
    { id: "ch-mixtos", cat: "alfajores", brand: "Chok", name: "Alfajor Chok Mixto", img: R("assets/catalog-pub/chok-mixtos.png"), desc: "Alfajor artesanal surtido, pote de ~200 g.", tags: ["Artesanal", "~200 g"], price: 3800 },
    { id: "ch-conitos", cat: "alfajores", brand: "Chok", name: "Alfajor Chok Conitos", img: R("assets/catalog-pub/chok-conitos.png"), desc: "Alfajor artesanal con conitos, pote de ~200 g.", tags: ["Artesanal", "~200 g"], price: 3800 },
    { id: "altc-alfajor", cat: "alfajores", brand: "Altas Cumbres", name: "Alfajor Cordobés x12", img: R("assets/catalog-pub/altascumbres-variedades.png"), desc: "Caja de 12 alfajores cordobeses, elaboración artesanal. Elegí el sabor.", tags: ["x12", "Artesanal"], price: 19500, variants: ["Higo-Pera", "Dulce de leche", "Membrillo-Durazno"] },

    // ---- Miel Pampa ----
    { id: "pm-solida", cat: "miel", brand: "Pampa", name: "Miel Pura Sólida", img: R("assets/catalog-pub/pampa-miel-solida.png"), desc: "Miel pura de pradera, cristalizada y untable. Elegí el tamaño. Se entrega por 6 unidades.", tags: ["100% natural", "x6"], variants: [{ name: "¼ kg", price: 19550 }, { name: "½ kg", price: 27550 }, { name: "1 kg", price: 44550 }] },
    { id: "pm-liquida", cat: "miel", brand: "Pampa", name: "Miel Pura Líquida", img: R("assets/catalog-pub/pampa-miel-liquida.png"), desc: "Miel pura de pradera, fluida y clara. Elegí el tamaño. Se entrega por 6 unidades.", tags: ["100% natural", "x6"], variants: [{ name: "¼ kg", price: 19550 }, { name: "½ kg", price: 27550 }, { name: "1 kg", price: 44550 }] },
    { id: "pm-panal", cat: "miel", brand: "Pampa", name: "Miel en Panal", img: R("assets/catalog-pub/pampa-miel-panal.png"), desc: "Panal natural en pote, miel pura de pradera.", tags: ["100% natural"], price: 4350 },
  ],
};
